
#ifndef A_SAVING_CERTIFICATES_MANAGEMENT_SYSTEM_CERTIFICATE_H
#define A_SAVING_CERTIFICATES_MANAGEMENT_SYSTEM_CERTIFICATE_H
#include <iostream>

using namespace std;


class Certificate {

};


#endif //A_SAVING_CERTIFICATES_MANAGEMENT_SYSTEM_CERTIFICATE_H
